name: assembleDevelopDebug

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDevelopDebug --stacktrace
        
      - name: Upload develop apk
        uses: actions/upload-artifact@v2
        with:
          name: app-develop-debug.apk
          path: app/build/outputs/apk/develop/debug/app-develop-debug.apk
